[package]
name = "smartrip"
version = "0.1.0"
authors = ["Cristian Iglesias <ciglesiasvera@gmail.com> Aldrin Díaz"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true